/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Studies */
        get: operations["list_studies_api_v1_studies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Approval */
        post: operations["record_approval_api_v1_studies__study_id__approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/claims/{claim_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_studies__study_id__claims__claim_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Package */
        post: operations["export_package_api_v1_studies__study_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/exports/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_studies__study_id__exports__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/section-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Section */
        post: operations["run_section_api_v1_studies__study_id__section_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sections */
        get: operations["list_sections_api_v1_studies__study_id__sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/sections/{section_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Section Draft */
        get: operations["get_section_draft_api_v1_studies__study_id__sections__section_id__draft_get"];
        put?: never;
        /** Generate Section Draft */
        post: operations["generate_section_draft_api_v1_studies__study_id__sections__section_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/validation-results/{result_id}/dispositions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Disposition */
        post: operations["record_disposition_api_v1_studies__study_id__validation_results__result_id__dispositions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/validation-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Validation */
        post: operations["run_validation_api_v1_studies__study_id__validation_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_studies__study_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Approval */
        Approval: {
            /** Approval Id */
            approval_id: string;
            /** Meaning */
            meaning: string;
            /** Reviewer */
            reviewer: string;
            role: components["schemas"]["ApprovalRole"];
            /** Timestamp */
            timestamp: string;
        };
        /** ApprovalCommand */
        ApprovalCommand: {
            /** Meaning */
            meaning: string;
            /** Reviewer */
            reviewer: string;
            role: components["schemas"]["ApprovalRole"];
        };
        /**
         * ApprovalRole
         * @enum {string}
         */
        ApprovalRole: "pathologist" | "peer_reviewer" | "qau" | "study_director";
        /** AssembledSection */
        AssembledSection: {
            /** Blocks */
            blocks: components["schemas"]["ReportBlock"][];
            /** Fields */
            fields: components["schemas"]["ReportFieldTemplate"][];
            /** Required Field Count */
            required_field_count: number;
            /** Section Id */
            section_id: string;
            status: components["schemas"]["SectionStatus"];
            /** Title */
            title: string;
        };
        /** Claim */
        Claim: {
            /** Claim Id */
            claim_id: string;
            /** Field Id */
            field_id: string;
            /** Grain */
            grain: string;
            /** Section Id */
            section_id: string;
            status: components["schemas"]["ClaimStatus"];
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "pending" | "validated" | "needs_review" | "approved";
        /** DispositionCommand */
        DispositionCommand: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "corrected" | "explained_in_nsdrg" | "approved_exception";
            /** Reason */
            reason: string;
            /** Reviewer */
            reviewer: string;
        };
        /**
         * DispositionDecision
         * @enum {string}
         */
        DispositionDecision: "open" | "corrected" | "explained_in_nsdrg" | "approved_exception" | "rejected";
        /** DoseGroup */
        DoseGroup: {
            /** Dose */
            dose: number;
            /** Dose Unit */
            dose_unit: string;
            /** Group Id */
            group_id: string;
            /** Label */
            label: string;
            /** Planned N Per Sex */
            planned_n_per_sex: number;
            /** Sexes */
            sexes: ("M" | "F")[];
            /** Study Id */
            study_id: string;
        };
        /** DraftRequest */
        DraftRequest: {
            /** Feedback */
            feedback?: string[];
        };
        /** EvidenceChain */
        EvidenceChain: {
            claim: components["schemas"]["Claim"];
            /** Exact Match */
            exact_match: boolean | null;
            /** Recomputed Value */
            recomputed_value: number | null;
            /** Report Text */
            report_text: string;
            /** Sources */
            sources: components["schemas"]["SourceRecord"][];
            /** Transform Id */
            transform_id: string | null;
            /** Validations */
            validations: components["schemas"]["ValidationResult"][];
        };
        /** ExportArtifact */
        ExportArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Checksum */
            checksum: string | null;
            /** Kind */
            kind: string;
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "exported";
        };
        /** ExportCommand */
        ExportCommand: {
            /** Actor */
            actor: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** ExportReceipt */
        ExportReceipt: {
            /** Artifacts */
            artifacts: components["schemas"]["ExportArtifact"][];
            /** Exported At */
            exported_at: string;
            /** Idempotent Replay */
            idempotent_replay: boolean;
            /**
             * Status
             * @constant
             */
            status: "exported";
            /** Study Id */
            study_id: string;
        };
        /** GateDecision */
        GateDecision: {
            /** Blocking Result Ids */
            blocking_result_ids: string[];
            /** Decided At */
            decided_at: string;
            /** Gate Id */
            gate_id: string;
            /**
             * Gate Type
             * @enum {string}
             */
            gate_type: "section" | "release";
            status: components["schemas"]["GateStatus"];
        };
        /**
         * GateStatus
         * @enum {string}
         */
        GateStatus: "blocked" | "ready_for_review" | "ready_for_signature" | "ready_for_export" | "exported";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ManifestEntry */
        ManifestEntry: {
            /** Artifact Id */
            artifact_id: string;
            /** Authority Tier */
            authority_tier: number;
            /** Authorized By */
            authorized_by: string;
            /** Checksum */
            checksum: string;
            /** Kind */
            kind: string;
            /** Locked */
            locked: boolean;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** NoteBlock */
        NoteBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "note";
            /** Text */
            text: string;
        };
        /** PlannerCapability */
        PlannerCapability: {
            /** Available */
            available: boolean;
            /** Detail */
            detail: string;
            /** Label */
            label: string;
            mode: components["schemas"]["PlannerMode"];
        };
        /**
         * PlannerMode
         * @enum {string}
         */
        PlannerMode: "fixture" | "openai_compatible";
        /** ProseBlock */
        ProseBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "prose";
            /** Markdown */
            markdown: string;
        };
        /** RegulatoryReference */
        RegulatoryReference: {
            /**
             * Authority
             * @enum {string}
             */
            authority: "regulation" | "guidance" | "standard" | "test_guideline";
            /** Binding */
            binding: boolean;
            /** Citation */
            citation: string;
            /** Reference Id */
            reference_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ReportAssembly */
        ReportAssembly: {
            /** Sections */
            sections: components["schemas"]["AssembledSection"][];
            template: components["schemas"]["ReportTemplate"];
        };
        /** ReportBlock */
        ReportBlock: {
            /** Block Id */
            block_id: string;
            /** Claim Id */
            claim_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "paragraph" | "claim" | "review_marker";
            /**
             * Provenance Count
             * @default 0
             */
            provenance_count: number;
            /** Text */
            text: string;
        };
        /** ReportFieldTemplate */
        ReportFieldTemplate: {
            /** Expected Grain */
            expected_grain: string;
            /** Field Id */
            field_id: string;
            /** Human Judgment */
            human_judgment: boolean;
            /** Label */
            label: string;
            /** Regulatory Reference Ids */
            regulatory_reference_ids: string[];
            /** Required */
            required: boolean;
            /** Source Expectation */
            source_expectation: string;
        };
        /** ReportSectionTemplate */
        ReportSectionTemplate: {
            /** Fields */
            fields: components["schemas"]["ReportFieldTemplate"][];
            /** Purpose */
            purpose: string;
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
        };
        /** ReportTemplate */
        ReportTemplate: {
            /** Ctd Location */
            ctd_location: string;
            /** Disclaimer */
            disclaimer: string;
            /** Name */
            name: string;
            /** References */
            references: components["schemas"]["RegulatoryReference"][];
            /** Sections */
            sections: components["schemas"]["ReportSectionTemplate"][];
            /** Study Type Id */
            study_type_id: string;
            /** Template Id */
            template_id: string;
            /** Version */
            version: string;
        };
        /** ReviewDisposition */
        ReviewDisposition: {
            decision: components["schemas"]["DispositionDecision"];
            /** Disposition Id */
            disposition_id: string;
            /** Reason */
            reason: string | null;
            /** Result Id */
            result_id: string;
            /** Reviewer */
            reviewer: string | null;
            /** Timestamp */
            timestamp: string | null;
        };
        /** SectionDraft */
        SectionDraft: {
            /** Blocks */
            blocks: (components["schemas"]["ProseBlock"] | components["schemas"]["TableBlock"] | components["schemas"]["NoteBlock"])[];
            /** Created At */
            created_at: string;
            /** Data Available */
            data_available: boolean;
            /** Feedback */
            feedback?: string[];
            /** Model */
            model?: string | null;
            /** Narrative Md */
            narrative_md?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Provenance Count
             * @default 0
             */
            provenance_count: number;
            /** Section Id */
            section_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "needs_review" | "proposed" | "verified" | "discarded" | "empty";
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** SectionDraftCandidate */
        SectionDraftCandidate: {
            /** Agent Receipt */
            agent_receipt: {
                [key: string]: string;
            };
            /** Attempt */
            attempt: number;
            /** Candidate Id */
            candidate_id: string;
            /** Content Blocks */
            content_blocks: {
                [key: string]: unknown;
            }[];
            /** Drafting Cycle Id */
            drafting_cycle_id: string;
            /** Executor Receipt Ids */
            executor_receipt_ids: string[];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.section-draft-candidate/v1";
            /** Section Id */
            section_id: string;
            /** Section Package Id */
            section_package_id: string;
            /** Section Package Version */
            section_package_version: string;
            /**
             * Status
             * @constant
             */
            status: "section_draft_candidate";
            /** Validated Claim Ids */
            validated_claim_ids: string[];
        };
        /** SectionListItem */
        SectionListItem: {
            /** Data Available */
            data_available?: boolean | null;
            /** Has Verified Claims */
            has_verified_claims: boolean;
            /** Order */
            order: number;
            /** Section Id */
            section_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "needs_review" | "proposed" | "verified" | "discarded" | "empty";
            /** Template Section */
            template_section: string | null;
            /** Title */
            title: string;
            /** Version */
            version?: number | null;
        };
        /** SectionRunCommand */
        SectionRunCommand: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Section Package Id */
            section_package_id: string;
        };
        /** SectionRunEligibility */
        SectionRunEligibility: {
            /** Eligible */
            eligible: boolean;
            /** Reasons */
            reasons: string[];
            /** Section Package Id */
            section_package_id: string;
        };
        /** SectionRunReceipt */
        SectionRunReceipt: {
            /**
             * Agent Runtime
             * @constant
             */
            agent_runtime: "codex_sdk";
            /** Candidate Hash */
            candidate_hash: string;
            /** Candidate Id */
            candidate_id: string;
            /** Codex Thread Id */
            codex_thread_id: string;
            /** Envelope Hash */
            envelope_hash: string;
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
            /** Review Scaffold Revision */
            review_scaffold_revision: number;
            /** Run Id */
            run_id: string;
            /** Section Id */
            section_id: string;
            /** Section Package Id */
            section_package_id: string;
            /** Skill Hash */
            skill_hash: string;
            /**
             * Skill Name
             * @constant
             */
            skill_name: "helix-section-agent";
            /**
             * Status
             * @constant
             */
            status: "candidate_recorded";
        };
        /**
         * SectionStatus
         * @enum {string}
         */
        SectionStatus: "validated" | "needs_review" | "reviewed";
        /** SourceRecord */
        SourceRecord: {
            /** Attributes */
            attributes: {
                [key: string]: string | number | null;
            };
            /** Domain */
            domain: string;
            /** Grain */
            grain: string;
            /** Record Id */
            record_id: string;
            /** Source Pointer */
            source_pointer: string;
            /** Unit */
            unit: string | null;
            /** Value */
            value: number | string;
        };
        /** Stage */
        Stage: {
            /** Boundary */
            boundary: string;
            /** Checks */
            checks: string[];
            /** Input Detail */
            input_detail: string;
            /** Input Title */
            input_title: string;
            /** Name */
            name: string;
            /** Output Detail */
            output_detail: string;
            /** Output Title */
            output_title: string;
            /**
             * Owner
             * @enum {string}
             */
            owner: "agent" | "human" | "hybrid";
            /** Stage Id */
            stage_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "current" | "blocked" | "pending";
            /** Summary */
            summary: string;
        };
        /** StoredSectionRun */
        StoredSectionRun: {
            candidate: components["schemas"]["SectionDraftCandidate"];
            /** Envelope */
            envelope: {
                [key: string]: unknown;
            };
            receipt: components["schemas"]["SectionRunReceipt"];
            /** Review Scaffold */
            review_scaffold: {
                [key: string]: unknown;
            };
        };
        /** Study */
        Study: {
            /** Dose Groups */
            dose_groups: components["schemas"]["DoseGroup"][];
            /** Duration Days */
            duration_days: number;
            /** Protocol Version */
            protocol_version: string;
            /** Route */
            route: string;
            /** Species */
            species: string;
            /** Study Id */
            study_id: string;
            /** Study Start */
            study_start: string;
            /** Study Type Id */
            study_type_id: string;
        };
        /** StudyListItem */
        StudyListItem: {
            /** Label */
            label: string;
            release_status: components["schemas"]["GateStatus"];
            /** Study Id */
            study_id: string;
            /** Study Type Id */
            study_type_id: string;
            /** Title */
            title: string;
            /** Workflow State */
            workflow_state: string;
        };
        /** TableBlock */
        TableBlock: {
            /** Columns */
            columns: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table";
            /** Rows */
            rows: string[][];
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationKind
         * @enum {string}
         */
        ValidationKind: "deterministic" | "agent_planned";
        /** ValidationRequest */
        ValidationRequest: {
            /** @default fixture */
            planner: components["schemas"]["PlannerMode"];
        };
        /** ValidationResult */
        ValidationResult: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** @default deterministic */
            kind: components["schemas"]["ValidationKind"];
            /** Message */
            message: string;
            /** Result Id */
            result_id: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version: string;
            /** Scope Id */
            scope_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "blocker";
            status: components["schemas"]["ValidationStatus"];
            /** Tool Name */
            tool_name?: string | null;
        };
        /** ValidationRun */
        ValidationRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Llm Used */
            llm_used: boolean;
            planner: components["schemas"]["PlannerMode"];
            /** Planner Label */
            planner_label: string;
            /** Results */
            results: components["schemas"]["ValidationResult"][];
            /** Rule Bundle Version */
            rule_bundle_version: string;
            /** Run Id */
            run_id: string;
            /** Study Id */
            study_id: string;
        };
        /**
         * ValidationStatus
         * @enum {string}
         */
        ValidationStatus: "pass" | "warn" | "fail" | "skipped";
        /** WorkflowEvent */
        WorkflowEvent: {
            /** Actor */
            actor: string;
            /** Details */
            details?: {
                [key: string]: string | number | boolean | null;
            };
            /** Event */
            event: string;
            /** Event Id */
            event_id: string;
            /** Outcome */
            outcome: string;
            /** Timestamp */
            timestamp: string;
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /** Approvals */
            approvals: components["schemas"]["Approval"][];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Dispositions */
            dispositions: components["schemas"]["ReviewDisposition"][];
            /** Events */
            events: components["schemas"]["WorkflowEvent"][];
            /** Export Artifacts */
            export_artifacts: components["schemas"]["ExportArtifact"][];
            /** Label */
            label: string;
            /** Manifest */
            manifest: components["schemas"]["ManifestEntry"][];
            /** Planner Capabilities */
            planner_capabilities: components["schemas"]["PlannerCapability"][];
            release_gate: components["schemas"]["GateDecision"];
            report: components["schemas"]["ReportAssembly"];
            /** Section Run Eligibility */
            section_run_eligibility: components["schemas"]["SectionRunEligibility"][];
            /** Section Runs */
            section_runs: components["schemas"]["StoredSectionRun"][];
            /** Stages */
            stages: components["schemas"]["Stage"][];
            study: components["schemas"]["Study"];
            summary: components["schemas"]["WorkspaceSummary"];
            /** Validations */
            validations: components["schemas"]["ValidationResult"][];
            /** Workflow State */
            workflow_state: string;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /** Blocker Count */
            blocker_count: number;
            /** Provenance Count */
            provenance_count: number;
            /** Record Count */
            record_count: number;
            /** Resolved Blocker Count */
            resolved_blocker_count: number;
            /** Section Count */
            section_count: number;
            /** Source Count */
            source_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_studies_api_v1_studies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyListItem"][];
                };
            };
        };
    };
    record_approval_api_v1_studies__study_id__approvals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_studies__study_id__claims__claim_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceChain"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_package_api_v1_studies__study_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_v1_studies__study_id__exports__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_section_api_v1_studies__study_id__section_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionRunCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionRunReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sections_api_v1_studies__study_id__sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_section_draft_api_v1_studies__study_id__sections__section_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionDraft"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_section_draft_api_v1_studies__study_id__sections__section_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_disposition_api_v1_studies__study_id__validation_results__result_id__dispositions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispositionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_validation_api_v1_studies__study_id__validation_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_studies__study_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
