import type { components } from "./api-schema";

export type Workspace = components["schemas"]["WorkspaceResponse"];
export type ValidationRun = components["schemas"]["ValidationRun"];
export type ValidationResult = components["schemas"]["ValidationResult"];
export type EvidenceChainData = components["schemas"]["EvidenceChain"];
export type Claim = components["schemas"]["Claim"];
export type Stage = components["schemas"]["Stage"];
export type AssembledSection = components["schemas"]["AssembledSection"];
export type ApprovalRole = components["schemas"]["ApprovalRole"];
export type ExportReceipt = components["schemas"]["ExportReceipt"];
export type PlannerMode = components["schemas"]["PlannerMode"];
export type SectionRunReceipt = components["schemas"]["SectionRunReceipt"];
export type SectionContentDraft = components["schemas"]["SectionContentDraft"];
export type SectionListItem = components["schemas"]["SectionListItem"];
export type SectionBlock = SectionContentDraft["blocks"][number];
export type ChatMessage = components["schemas"]["ChatMessage"];
export type ChatScope = ChatMessage["scope"];
export type ChatTurn = components["schemas"]["ChatTurn"];
export type DataValidationExecution = components["schemas"]["DataValidationExecution"];
export type CandidateEvaluation = components["schemas"]["CandidateEvaluation"];
export type CrossSectionQueryReceipt = components["schemas"]["CrossSectionQueryReceipt"];
export type SectionDraft = components["schemas"]["SectionDraft"];
export type PromotionDecision = components["schemas"]["PromotionDecision"];
export type HumanDirectedRevisionReceipt = components["schemas"]["HumanDirectedRevisionReceipt"];
export type DraftingCycle = components["schemas"]["DraftingCycle"];
