"""baseline: study packages, audit events, exports, validation runs, section runs

Revision ID: bf13e5f55c15
Revises: 
Create Date: 2026-09-24 15:08:21.687776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# autogenerate renders JSON variants as JSONB(astext_type=Text())
# but does not import Text itself.
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf13e5f55c15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_audit_idempotency')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_study_id'), ['study_id'], unique=False)

    op.create_table('candidate_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('candidate_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('evaluation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_candidate_evaluation_key')
    )
    with op.batch_alter_table('candidate_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_evaluations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_evaluations_study_id'), ['study_id'], unique=False)

    op.create_table('cross_section_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('receipt', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_cross_section_query_key')
    )
    with op.batch_alter_table('cross_section_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cross_section_queries_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cross_section_queries_study_id'), ['study_id'], unique=False)

    op.create_table('data_validation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('package_id', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('execution', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_data_validation_key')
    )
    with op.batch_alter_table('data_validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_validation_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_validation_runs_study_id'), ['study_id'], unique=False)

    op.create_table('drafting_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('cycle_id', sa.String(length=80), nullable=False),
    sa.Column('section_package_id', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('cycle', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('stale_disposition_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('stale_approval_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('review_scaffold_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'cycle_id', name='uq_drafting_cycle_id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_drafting_cycle_key')
    )
    with op.batch_alter_table('drafting_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafting_cycles_study_id'), ['study_id'], unique=False)

    op.create_table('export_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('artifact_id', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('checksum', sa.String(length=80), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'artifact_id', name='uq_export_file')
    )
    with op.batch_alter_table('export_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_files_study_id'), ['study_id'], unique=False)

    op.create_table('pinned_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_pinned_run_key')
    )
    with op.batch_alter_table('pinned_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pinned_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pinned_runs_study_id'), ['study_id'], unique=False)

    op.create_table('promotion_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('candidate_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_promotion_decision_key')
    )
    with op.batch_alter_table('promotion_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_decisions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_decisions_study_id'), ['study_id'], unique=False)

    op.create_table('section_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('candidate_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('draft', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'candidate_id', name='uq_section_draft_candidate'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_section_draft_key')
    )
    with op.batch_alter_table('section_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_drafts_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_drafts_study_id'), ['study_id'], unique=False)

    op.create_table('section_runs',
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('section_package_id', sa.String(length=120), nullable=False),
    sa.Column('drafting_cycle_id', sa.String(length=80), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('envelope', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('candidate', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('receipt', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('review_scaffold', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('study_id', 'idempotency_key', name='uq_section_run_key'),
    sa.UniqueConstraint('study_id', 'section_package_id', 'drafting_cycle_id', 'attempt', name='uq_section_run_attempt')
    )
    with op.batch_alter_table('section_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_runs_study_id'), ['study_id'], unique=False)

    op.create_table('study_packages',
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('package_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('study_id'),
    sa.UniqueConstraint('package_id')
    )
    op.create_table('validation_runs',
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('planner_mode', sa.String(length=40), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('planner_label', sa.String(length=120), nullable=False),
    sa.Column('rule_bundle_version', sa.String(length=40), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_runs_study_id'), ['study_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_runs_study_id'))

    op.drop_table('validation_runs')
    op.drop_table('study_packages')
    with op.batch_alter_table('section_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_runs_study_id'))

    op.drop_table('section_runs')
    with op.batch_alter_table('section_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_drafts_study_id'))
        batch_op.drop_index(batch_op.f('ix_section_drafts_run_id'))

    op.drop_table('section_drafts')
    with op.batch_alter_table('promotion_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_decisions_study_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_decisions_run_id'))

    op.drop_table('promotion_decisions')
    with op.batch_alter_table('pinned_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pinned_runs_study_id'))
        batch_op.drop_index(batch_op.f('ix_pinned_runs_run_id'))

    op.drop_table('pinned_runs')
    with op.batch_alter_table('export_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_files_study_id'))

    op.drop_table('export_files')
    with op.batch_alter_table('drafting_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafting_cycles_study_id'))

    op.drop_table('drafting_cycles')
    with op.batch_alter_table('data_validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_validation_runs_study_id'))
        batch_op.drop_index(batch_op.f('ix_data_validation_runs_run_id'))

    op.drop_table('data_validation_runs')
    with op.batch_alter_table('cross_section_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cross_section_queries_study_id'))
        batch_op.drop_index(batch_op.f('ix_cross_section_queries_run_id'))

    op.drop_table('cross_section_queries')
    with op.batch_alter_table('candidate_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_evaluations_study_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_evaluations_run_id'))

    op.drop_table('candidate_evaluations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_study_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
