"""intake jobs

Revision ID: ea600664952b
Revises: bf13e5f55c15
Create Date: 2026-09-24 15:22:37.574061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea600664952b'
down_revision: Union[str, Sequence[str], None] = 'bf13e5f55c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_jobs',
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('study_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('stages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('receipt', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_intake_job_key')
    )
    with op.batch_alter_table('intake_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intake_jobs_study_id'), ['study_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_jobs_study_id'))
        batch_op.drop_index(batch_op.f('ix_intake_jobs_status'))

    op.drop_table('intake_jobs')
    # ### end Alembic commands ###
